### PR TITLE
Update to Angular 6 generated library

### PR DESCRIPTION
**Pull request by kayvanbree**
I copy-pasted everything into a new project. This still needs to be done, I'll update my PR with more commits:

- Update .travis.yml to reflect new building process
- Do something with .eslint (I don't know it, so I don't know what)
- Do something with codeclimate (same as .eslint)
- Update deployment to reflect new building process
- ~~Do something with testing (if there were any tests in the previous project, when I ran it it found no tests)~~
- Check peerDependencies and see if we need any (if there is an imported library we expose in some signature, we need to add that)
- ~~Add live reload for lazy reasons (https://mereommig.dk/en/blog/adding-livereload-to-the-angular-cli-libraries)~~
- ~~Update README (new scripts for running demo, building, etc)~~
- Copy readme on build in travis
- Test it`
- update package.json

### CODE REVIEW

**Comment by kayvanbree** [comment]
There are 2 readme's right now. Maybe we can just use the readme in root and copy it before building the library in travis, so the npm package will also include the readme. Same goes for changelog and license I guess.

**Comment by kayvanbree** [comment]
I haven't had much spare time lately. I'll work on this when I have time.

**Comment by kayvanbree** [comment]
@Nolanus It looks like your tests did nothing (exit 0 as script), so I just removed the old stuff from the travis file for now (manual building and running the demo application and the fake test). I don't really know what your goal is for testing, building and deploying so I need some help there.

**Comment by Nolanus** [comment]
Hi,

correct, I never tackled writing tests and the `npm test` command did nothing.
Integration tests are favorable, but probably quite/too complicated to achieve and will be too fragile (running two browser instances in a headless environment, manage their synchronization, ...).
So maybe basic unit tests for the MultiWindowService are useful, mocking the StorageService.

**Comment by kayvanbree** [comment]
@Nolanus You can actually test multi-window stuff, if you use the right approach. [Cypress ](https://www.cypress.io/) is a fairly new (and awesome!) testing framework that has some articles about testing multi-window stuff without actually opening multiple windows (that's impossible in Cypress). It can be found in the [trade-offs page](https://docs.cypress.io/guides/references/trade-offs.html#Permanent-trade-offs-1). 

I'll see if I have some time to write some test, but I can't promise anything. Can you tell me what still needs to be done to merge this PR?

**Comment by kayvanbree** [comment]
@Nolanus The Code quality check checks for configuration stuff that's generated like this. It should not fail there. Can you take a look at this PR? We can always set up testing later.

**Pull request merged**
